apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test
spec:
  ports:
  - name: 80-800
    port: 80
    protocol: TCP
    targetPort: 800
  selector:
    app: test
  type: NodePort
status:
  loadBalancer: {}
