apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: test
  namespace: node-port
spec:
  ports:
  - name: 80-800
    port: 80
    protocol: TCP
    targetPort: 800
  selector:
    app: app
  type: NodePort
status:
  loadBalancer: {}
