name: CI stage

on: 
  push:
    branch:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2

     # - name: SonarQube Scan
     #   uses: SonarSource/sonarqube-scan-action@master
     #   env:
     #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: |
          cd app
          npm install

      - name: Run test
        run: |
          cd app
          npm test

      - name: Docker Build Validation
        run: |
          docker build -t devsecops-app:${{ github.sha }} .

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: devsecops-app:${{ github.sha }}
          format: table
          severity: CRITICAL,HIGH
